name = "LoopVectorization"
uuid = "bdcacae8-1622-11e9-2a5c-532679323890"
authors = ["Chris Elrod <elrodc@gmail.com>"]
version = "0.12.94"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
CloseOpenIntervals = "fb6a15b2-703c-40df-9091-08a04967cfa9"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
HostCPUFeatures = "3e5b6fbb-0976-4d2c-9146-d79de83f2fb0"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
LayoutPointers = "10f19ff3-798f-405d-979b-55457f8fc047"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
PolyesterWeave = "1d0040c9-8b98-4ee7-8388-3f51789ca0ad"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SIMDDualNumbers = "3cdde19b-5bb0-4aaf-8931-af3e248e098b"
SLEEFPirates = "476501e8-09a2-5ece-8869-fb82de89a1fa"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
ThreadingUtilities = "8290d209-cae3-49c0-8002-c8c24d57dab5"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
VectorizationBase = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"

[compat]
ArrayInterface = "3.1.32"
CPUSummary = "0.1.3"
CloseOpenIntervals = "0.1.2"
DocStringExtensions = "0.8"
HostCPUFeatures = "0.1.3"
IfElse = "0.1"
LayoutPointers = "0.1.2"
OffsetArrays = "1.4.1"
PolyesterWeave = "0.1"
Requires = "1"
SIMDDualNumbers = "0.1"
SLEEFPirates = "0.6.23"
Static = "0.3.3, 0.4"
ThreadingUtilities = "0.4.5"
UnPack = "1"
VectorizationBase = "0.21.21"
julia = "1.5"
